version: "3.5"



services:
  e-flask-api:
    build:
      context: .
    restart: unless-stopped
    container_name: e-flask-api
    ports:
      - 5000:5000
  
  eg-prmetheus:
    image: prom/prometheus:latest
    container_name: eg-prmetheus
    restart: unless-stopped
    ports: 
      - 9090:9090
    volumes: 
      - ./config_files/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'

  eg-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: eg-grafana
    depends_on: 
      - eg-prmetheus
    ports: 
      - 3000:3000
    volumes: 
      - ./config_files/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file: 
      - ./config_files/config.monitoring