global:
  scrape_interval:     15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['eg-prmetheus:9090']

  - job_name: 'todo'
    scrape_interval: 5s
    static_configs:
    - targets: ['e-flask-api:5000']


